
export const products=[
    {
        id:'1',
        image:'https://zandokh.com/image/cache/catalog/products/2024-11/2122410897/IMG_2556-cr-450x672.jpg',
        dategory:'man',
        reqular_price:'$12.95',
        sale_price:'9.95',
        title:'T-Shirts',
        view:'11',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M L XL',
        color:'Write Black Blue',
        icon:''
    },
    {
        id:'2',
        image:'https://zandokh.com/image/cache/catalog/products/2024-11/2122408791/RegularHooded%20(2)-cr-450x672.jpg',
        dategory:'man',
        reqular_price:'$12.98',
        sale_price:'6.98',
        title:'Regular Hooded',
        view:'15',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M L XL',
        color:'Write Black Blue',
        icon:''

    },
    {
        id:'3',
        image:'https://zandokh.com/image/cache/catalog/products/2024-11/2122410902/Regular-Fitted-Tank-Top%20(1)-cr-450x672.jpg',
        dategory:'man',
        reqular_price:'$11.97',
        sale_price:' 5.97',
        title:'Fitted Tank',
        view:'3',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M L XL',
        color:'Write Black Blue',

    },
    {
        id:'4',
        image:'https://zandokh.com/image/cache/catalog/products/2024-11/2122408761/OversizedT-Shirts%20(2)-cr-450x672.jpg',
        dategory:'man',
        reqular_price:'$12.95',
        sale_price:'6.95',
        title:'Regular Tank',
        view:'8',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M L XL',
        color:'Write Black Blue',

    },
    {
        id:'5',
        image:'https://zandokh.com/image/cache/catalog/products/2024-11/2122410914/Relaxed-Fit-T-Shirts%20(3)-cr-450x672.jpg',
        dategory:'man',
        reqular_price:'$14.75',
        sale_price:'8.75',
        title:'Relaxed Fit',
        view:'19',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M L XL',
        color:'Write Black Blue',

    },
    {
        id:'6',
        image:'https://zandokh.com/image/cache/catalog/products/2024-11/1222409607/Loose-Fit-Shirts%20(8)-cr-450x672.jpg',
        dategory:'man',
        reqular_price:'',
        sale_price:'11.75',
        title:'Loose Fit',
        view:'22',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M L XL',
        color:'Write Black Blue',

    },
    {
        id:'7',
        image:'https://zandokh.com/image/cache/catalog/products/2024-11/1122410353/T-Shirt%20(1)-cr-450x672.jpg',
        dategory:'man',
        reqular_price:'',
        sale_price:'14.97',
        title:'Oversized',
        view:'10',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'L XL',
        color:'Write Black Blue',

    },
    {
        id:'8',
        image:'https://zandokh.com/image/cache/catalog/products/2024-10/1122410004/Oversized-T-shirts%20(2)-cr-450x672.jpg',
        dategory:'man',
        reqular_price:'',
        sale_price:'13.55',
        title:'Straight Fit',
        view:'16',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M L XL',
        color:'Write Black Blue',

    },
    {
        id:'9',
        image:'https://zandokh.com/image/cache/catalog/products/2024-11/1122409361/Relaxed%20Shirts%20(3)-cr-450x672.jpg',
        dategory:'man',
        reqular_price:'',
        sale_price:'14.75',
        title:'Regular Shirts',
        view:'30',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'M L XL',
        color:'Write Black Blue',

    },
    {
        id:'10',
        image:'https://zandokh.com/image/cache/catalog/products/2024-11/2112409684/Regular-Stripped-Shirts%20(1)-cr-450x672.jpg',
        dategory:'man',
        reqular_price:'',
        sale_price:'12.35',
        title:'Regular Stripped',
        view:'25',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'L XL',
        color:'Write Black Blue',

    },
    {
        id:'11',
        image:'https://zandokh.com/image/cache/catalog/products/2024-10/2222409892/Loose-Fit-T-shirts%20(2)-1-cr-450x672.jpg',
        dategory:'woman',
        reqular_price:'$14.75',
        sale_price:'8.75',
        title:'Unisex Loose',
        view:'22',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M L ',
        color:'Write Black Blue',

    },
    {
        id:'12',
        image:'https://zandokh.com/image/catalog/products/2024-11/1222410694/Cargo-Trousers%20(1).jpg',
        dategory:'woman',
        reqular_price:'$13.45',
        sale_price:'7.45',
        title:'Rugby Sweatshirt',
        view:'26',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M ',
        color:'Write Black Blue',

    },
    {
        id:'13',
        image:'https://zandokh.com/image/cache/catalog/products/2024-11/2222410897/T-Shirt%20(3)-cr-450x672.jpg',
        dategory:'woman',
        reqular_price:'$12.17',
        sale_price:'7.17',
        title:'Oversized T-shirts',
        view:'12',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M XL',
        color:'Write Black Blue',

    },
    {
        id:'14',
        image:'https://zandokh.com/image/cache/catalog/products/2024-11/2222408908/Cropped-Fitted-T-Shirts%20(13)-cr-450x672.jpg',
        dategory:'woman',
        reqular_price:'$11.75',
        sale_price:'5.75',
        title:'Cropped Fitted',
        view:'19',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M L XL',
        color:'Write Black Blue',

    },
    {
        id:'15',
        image:'https://zandokh.com/image/cache/catalog/products/2024-11/2222408905/Cropped%20T-Shirts%20(2)-cr-450x672.jpg',
        dategory:'woman',
        reqular_price:'$13.77',
        sale_price:'7.77',
        title:'Cropped T-Shirts',
        view:'20',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M L XL',
        color:'Write Black Blue',

    },
    {
        id:'16',
        image:'https://zandokh.com/image/cache/catalog/products/2024-11/2222408906/Cropped-Corset-Tops%20(2)-cr-450x672.jpg',
        dategory:'woman',
        reqular_price:'',
        sale_price:'12.35',
        title:'Cropped Corset',
        view:'44',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M L XL',
        color:'Write Black Blue',

    },
    {
        id:'17',
        image:'https://zandokh.com/image/cache/catalog/products/2024-11/2222410947/T-Shirt%20(3)-cr-450x672.jpg',
        dategory:'woman',
        reqular_price:'',
        sale_price:'13.75',
        title:'Cropped Fitted',
        view:'11',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M L XL',
        color:'Write Black Blue',

    },
    {
        id:'18',
        image:'https://zandokh.com/image/cache/catalog/products/2024-11/2222410941/Knitted-Cardigan%20(1)-cr-450x672.jpg',
        dategory:'woman',
        reqular_price:'',
        sale_price:'14.15',
        title:'RKnitted Cardigan',
        view:'20',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M L XL',
        color:'Write Black Blue',

    },
    {
        id:'19',
        image:'https://zandokh.com/image/cache/catalog/products/2024-11/2222408907/Regular-Fit-T-Shirts%20(2)-cr-450x672.jpg',
        dategory:'woman',
        reqular_price:'',
        sale_price:'12.17',
        title:'Regular Fit',
        view:'32',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M L XL',
        color:'Write Black Blue',

    },
    {
        id:'20',
        image:'https://zandokh.com/image/cache/catalog/products/2024-11/2222408910/Cropped-Polo-Shirts%20(3)-cr-450x672.jpg',
        dategory:'woman',
        reqular_price:'',
        sale_price:'15.75',
        title:'Cropped Polo',
        view:'14',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M L XL',
        color:'Write Black Blue',

    },
    {
        id:'21',
        image:'https://zandokh.com/image/catalog/products/2024-08/5152405105/Sport-Life-Sweatshirt%20(3).jpg',
        dategory:'boy',
        reqular_price:'$26.95',
        sale_price:'13.47',
        title:'Life Sweatshirt',
        view:'11',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M L XL',
        color:'Write Black Blue',
        icon:''
    },
    {
        id:'22',
        image:'https://zandokh.com/image/catalog/products/2024-08/5152405107/Sport-Life-Hoodie%20(2).jpg',
        dategory:'boy',
        reqular_price:'$35.95',
        sale_price:'10.79',
        title:'Life Hoodie',
        view:'15',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M L XL',
        color:'Write Black Blue',
        icon:''

    },
    {
        id:'23',
        image:'https://zandokh.com/image/catalog/products/2024-08/5152405087/Sport-Life-T-Shirt%20(2).jpg',
        dategory:'boy',
        reqular_price:'$10.59',
        sale_price:'5.29',
        title:'Life T-Shirt',
        view:'3',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M L XL',
        color:'Write Black Blue',

    },
    {
        id:'24',
        image:'https://zandokh.com/image/catalog/products/2024-07/5152405094/Tank%20(2).jpg',
        dategory:'boy',
        reqular_price:'$12.59',
        sale_price:'6.29',
        title:'Knitted Vest',
        view:'8',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M L XL',
        color:'Write Black Blue',

    },
    {
        id:'25',
        image:'https://zandokh.com/image/catalog/products/2024-02/1322312061/Sweatshirt%20(7).jpg',
        dategory:'boy',
        reqular_price:'$11.59',
        sale_price:'5.80',
        title:'Striped Sweatshirts',
        view:'19',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M L XL',
        color:'Write Black Blue',

    },
    {
        id:'26',
        image:'https://zandokh.com/image/catalog/products/2024-01/1422312187/Crewneck-T-Shirt%20(3).jpg',
        dategory:'girl',
        reqular_price:'$9.95',
        sale_price:'1.99',
        title:'Crewneck T-Shir',
        view:'22',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M L XL',
        color:'Write Black Blue',

    },
    {
        id:'27',
        image:'https://zandokh.com/image/catalog/products/2023-09/1422308033/Jersey-Bow-Tied-Top%20(6).jpg',
        dategory:'girl',
        reqular_price:'',
        sale_price:'9.97',
        title:'Oversized T-Shirt',
        view:'10',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'L XL',
        color:'Write Black Blue',

    },
    {
        id:'28',
        image:'https://zandokh.com/image/catalog/products/2024-11/1422410291/Printed-T-shirt%20(2).jpg',
        dategory:'girl',
        reqular_price:'',
        sale_price:'8.59',
        title:'Printed T-shirt',
        view:'16',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'S M L XL',
        color:'Write Black Blue',

    },
    {
        id:'29',
        image:'https://zandokh.com/image/catalog/products/2024-08/1422403216/Top%20(11).jpg',
        dategory:'girl',
        reqular_price:'',
        sale_price:'9.59',
        title:'T-Shirt',
        view:'30',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'M L XL',
        color:'Write Black Blue',

    },
    {
        id:'30',
        image:'https://zandokh.com/image/catalog/products/2024-07/1422403215/T-Shirt%20(10).jpg',
        dategory:'girl',
        reqular_price:'',
        sale_price:'9.59',
        title:'T-Shirt',
        view:'25',
        desscription:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, vel.',
        siz:'L XL',
        color:'Write Black Blue',

    },
    
];